#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.9pre
#

from settings import MAIN_SETTINGS, I_PATH
import wx
import os


class MultiChoice(wx.Dialog):
    def __init__(self, parent, caption, message, choices=[]):
        wx.Dialog.__init__(
            self, parent, style=wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER
        )

        try:
            size = MAIN_SETTINGS["ChoiceDialog"]
            self.SetSize((size["W"], size["H"]))
        except:
            self.SetSize((385, 278))
        self.SetTitle(caption)
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(
            wx.Bitmap(
                os.path.join(I_PATH, "sc.ico"), wx.BITMAP_TYPE_ANY
            )
        )
        self.SetIcon(_icon)
        self.SetFocus()

        self.sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self, wx.ID_ANY, message)
        self.sizer_1.Add(label_1, 0, wx.ALL, 10)

        self.check_list_box_1 = wx.CheckListBox(
            self, wx.ID_ANY, choices=choices, style=wx.LB_EXTENDED
        )
        self.sizer_1.Add(
            self.check_list_box_1, 1, wx.BOTTOM | wx.EXPAND | wx.LEFT | wx.RIGHT, 10
        )

        static_line_1 = wx.StaticLine(self, wx.ID_ANY)
        self.sizer_1.Add(static_line_1, 0, wx.EXPAND | wx.LEFT | wx.RIGHT, 10)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_1.Add(sizer_2, 0, wx.ALL | wx.EXPAND, 5)

        self.checkbox_1 = wx.CheckBox(
            self, wx.ID_ANY, "Select all", style=wx.CHK_2STATE
        )
        sizer_2.Add(self.checkbox_1, 0, wx.ALIGN_CENTER_VERTICAL | wx.LEFT, 5)

        sizer_2.Add((20, 20), 1, wx.EXPAND, 0)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        sizer_2.Add(self.button_OK, 0, wx.BOTTOM | wx.TOP, 5)
        self.button_OK.SetDefault()

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.Add(self.button_CANCEL, 0, wx.ALL, 5)

        self.SetSizer(self.sizer_1)
        # self.sizer_1.SetSizeHints(self)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()

        self.Bind(wx.EVT_CHECKBOX, self.EvtChBox, self.checkbox_1)
        self.Bind(wx.EVT_CLOSE, self.onCancel, id=wx.ID_ANY)
        self.Bind(wx.EVT_SIZE, self.size_frame, id=-1)
        # end wxGlade

    def GetSelections(self):
        return self.check_list_box_1.GetCheckedItems()

    def EvtChBox(self, event):
        state = self.checkbox_1.IsChecked()
        for i in range(self.check_list_box_1.GetCount()):
            self.check_list_box_1.Check(i, state)
        event.Skip()

    def size_frame(self, event):
        """"""
        width, height = event.GetSize()
        MAIN_SETTINGS["ChoiceDialog"] = {"W": width, "H": height}
        event.Skip()

    def onCancel(self, event):
        self.Destroy()


class MyApp(wx.App):
    def OnInit(self):
        self.dialog = MultiChoice(None, wx.ID_ANY, "")
        self.SetTopWindow(self.dialog)
        self.dialog.ShowModal()
        self.dialog.Destroy()
        return True


if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
