#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.0a8
#
import os
import pickle

from settings import FILE_SETTINGS, name_data
import logging.config

import wx

logger = logging.getLogger(__name__)


class FileSettings(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FileSettings.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((314, 334))
        self.SetTitle("File settings")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(
            wx.Bitmap(
                os.path.join("resources", "icons", "tool.ico"), wx.BITMAP_TYPE_ANY
            )
        )
        self.SetIcon(_icon)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.NB_1 = wx.Notebook(self, wx.ID_ANY)
        sizer_1.Add(self.NB_1, 1, wx.ALL | wx.EXPAND, 3)

        self.nb_pane1 = wx.Panel(self.NB_1, wx.ID_ANY)
        self.nb_pane1.SetBackgroundColour(
            wx.SystemSettings.GetColour(wx.SYS_COLOUR_3DFACE)
        )
        self.NB_1.AddPage(self.nb_pane1, "Ekstenzije fajlova")

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)

        self.sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add(self.sizer_5, 0, wx.ALL | wx.EXPAND, 4)

        labelFont = wx.Font(
            9,
            wx.FONTFAMILY_SWISS,
            wx.FONTSTYLE_ITALIC,
            wx.FONTWEIGHT_NORMAL,
            0,
            "Franklin Gothic Medium",
        )

        label_1 = wx.StaticText(
            self.nb_pane1, wx.ID_ANY, u"Ćirilica ANSI", style=wx.ALIGN_LEFT
        )
        label_1.SetFont(labelFont)
        self.sizer_5.Add(label_1, 0, wx.ALL | wx.EXPAND, 5)

        self.text_1 = wx.TextCtrl(
            self.nb_pane1, wx.ID_ANY, "cyr", style=wx.TE_PROCESS_ENTER
        )
        self.text_1.SetMinSize((125, 23))
        self.sizer_5.Add(self.text_1, 0, wx.BOTTOM | wx.LEFT | wx.RIGHT, 5)

        label_3 = wx.StaticText(
            self.nb_pane1, wx.ID_ANY, u"Ćirilica utf-8 srt", style=wx.ALIGN_LEFT
        )
        label_3.SetFont(labelFont)
        self.sizer_5.Add(label_3, 0, wx.ALL | wx.EXPAND, 5)

        self.text_2 = wx.TextCtrl(
            self.nb_pane1, wx.ID_ANY, "cyr_utf8", style=wx.TE_PROCESS_ENTER
        )
        self.text_2.SetMinSize((125, 23))
        self.sizer_5.Add(self.text_2, 0, wx.BOTTOM | wx.LEFT | wx.RIGHT, 5)

        label_6 = wx.StaticText(
            self.nb_pane1, wx.ID_ANY, "Latinica utf-8 srt", style=wx.ALIGN_LEFT
        )
        label_6.SetFont(labelFont)
        self.sizer_5.Add(label_6, 0, wx.ALL | wx.EXPAND, 5)

        self.text_3 = wx.TextCtrl(
            self.nb_pane1, wx.ID_ANY, "utf8", style=wx.TE_PROCESS_ENTER
        )
        self.text_3.SetMinSize((125, 23))
        self.sizer_5.Add(self.text_3, 0, wx.BOTTOM | wx.LEFT | wx.RIGHT, 5)

        label_7 = wx.StaticText(
            self.nb_pane1, wx.ID_ANY, "Transkribovan srt", style=wx.ALIGN_LEFT
        )
        label_7.SetFont(labelFont)
        self.sizer_5.Add(label_7, 0, wx.ALL | wx.EXPAND, 5)

        self.text_4 = wx.TextCtrl(
            self.nb_pane1, wx.ID_ANY, "changed", style=wx.TE_PROCESS_ENTER
        )
        self.text_4.SetMinSize((125, 23))
        self.sizer_5.Add(self.text_4, 0, wx.LEFT | wx.RIGHT, 5)

        self.sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add(self.sizer_6, 0, wx.ALL | wx.EXPAND, 4)

        label_2 = wx.StaticText(
            self.nb_pane1, wx.ID_ANY, u"Ćirilica utf-8 txt", style=wx.ALIGN_LEFT
        )
        label_2.SetFont(labelFont)
        self.sizer_6.Add(label_2, 0, wx.ALL | wx.EXPAND, 5)

        self.text_5 = wx.TextCtrl(
            self.nb_pane1, wx.ID_ANY, "cyr_utf8", style=wx.TE_PROCESS_ENTER
        )
        self.text_5.SetMinSize((125, 23))
        self.sizer_6.Add(self.text_5, 0, wx.BOTTOM | wx.LEFT | wx.RIGHT, 5)

        label_4 = wx.StaticText(
            self.nb_pane1, wx.ID_ANY, "Latinica ansi srt", style=wx.ALIGN_LEFT
        )
        label_4.SetFont(labelFont)
        self.sizer_6.Add(label_4, 0, wx.ALL | wx.EXPAND, 5)

        self.text_6 = wx.TextCtrl(
            self.nb_pane1, wx.ID_ANY, "lat", style=wx.TE_PROCESS_ENTER
        )
        self.text_6.SetMinSize((125, 23))
        self.sizer_6.Add(self.text_6, 0, wx.BOTTOM | wx.LEFT | wx.RIGHT, 5)

        label_5 = wx.StaticText(
            self.nb_pane1, wx.ID_ANY, "Fixed srt", style=wx.ALIGN_LEFT
        )
        label_5.SetFont(labelFont)
        self.sizer_6.Add(label_5, 0, wx.ALL | wx.EXPAND, 5)

        self.text_7 = wx.TextCtrl(
            self.nb_pane1, wx.ID_ANY, "fixed", style=wx.TE_PROCESS_ENTER
        )
        self.text_7.SetMinSize((125, 23))
        self.sizer_6.Add(self.text_7, 0, wx.BOTTOM | wx.LEFT | wx.RIGHT, 5)

        label_8 = wx.StaticText(
            self.nb_pane1, wx.ID_ANY, "Cleanup srt", style=wx.ALIGN_LEFT
        )
        label_8.SetFont(labelFont)
        self.sizer_6.Add(label_8, 0, wx.ALL | wx.EXPAND, 5)

        self.text_8 = wx.TextCtrl(
            self.nb_pane1, wx.ID_ANY, "cln", style=wx.TE_PROCESS_ENTER
        )
        self.text_8.SetMinSize((125, 23))
        self.sizer_6.Add(self.text_8, 0, wx.LEFT | wx.RIGHT, 5)

        self.nb_pane_2 = wx.Panel(self.NB_1, wx.ID_ANY)
        self.nb_pane_2.SetBackgroundColour(
            wx.SystemSettings.GetColour(wx.SYS_COLOUR_3DFACE)
        )
        self.NB_1.AddPage(self.nb_pane_2, u"Eksport Zip podešavanja")

        self.sizer_7 = wx.BoxSizer(wx.HORIZONTAL)

        self.sizer_8 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_7.Add(self.sizer_8, 1, wx.ALL, 6)

        self.label_9 = wx.StaticText(
            self.nb_pane_2, wx.ID_ANY, u"Ćirilica ANSI", style=wx.ALIGN_LEFT
        )
        self.label_9.SetFont(labelFont)
        self.sizer_8.Add(self.label_9, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 6)

        self.text_9 = wx.TextCtrl(
            self.nb_pane_2, wx.ID_ANY, "Cyr-ansi", style=wx.TE_PROCESS_ENTER
        )
        self.text_9.SetMinSize((125, 23))
        self.sizer_8.Add(self.text_9, 0, wx.ALL, 6)

        self.label_10 = wx.StaticText(
            self.nb_pane_2, wx.ID_ANY, "Latinica ANSI", style=wx.ALIGN_LEFT
        )
        self.label_10.SetFont(labelFont)
        self.sizer_8.Add(self.label_10, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 6)

        self.text_10 = wx.TextCtrl(
            self.nb_pane_2, wx.ID_ANY, "Lat-ansi", style=wx.TE_PROCESS_ENTER
        )
        self.text_10.SetMinSize((125, 23))
        self.sizer_8.Add(self.text_10, 0, wx.ALL, 6)

        self.label_11 = wx.StaticText(
            self.nb_pane_2,
            wx.ID_ANY,
            "Kreirani ZIP folderi\nu opciji Eksport ZIP multiple",
            style=wx.ALIGN_LEFT,
        )
        self.label_11.SetMinSize((125, 125))
        self.label_11.SetFont(
            wx.Font(
                10,
                wx.FONTFAMILY_SWISS,
                wx.FONTSTYLE_NORMAL,
                wx.FONTWEIGHT_NORMAL,
                0,
                "Franklin Gothic Medium",
            )
        )
        self.sizer_8.Add(self.label_11, 1, wx.ALL | wx.EXPAND, 5)

        self.sizer_9 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_7.Add(self.sizer_9, 1, wx.ALL, 6)

        self.label_13 = wx.StaticText(
            self.nb_pane_2, wx.ID_ANY, u"Ćirilica UTF-8", style=wx.ALIGN_LEFT
        )
        self.label_13.SetFont(labelFont)
        self.sizer_9.Add(self.label_13, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 6)

        self.text_11 = wx.TextCtrl(
            self.nb_pane_2, wx.ID_ANY, "Cyr-utf8", style=wx.TE_PROCESS_ENTER
        )
        self.text_11.SetMinSize((125, 23))
        self.sizer_9.Add(self.text_11, 0, wx.ALL, 6)

        self.label_14 = wx.StaticText(
            self.nb_pane_2, wx.ID_ANY, "Latinica UTF-8", style=wx.ALIGN_LEFT
        )
        self.label_14.SetFont(labelFont)
        self.sizer_9.Add(self.label_14, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 6)

        self.text_12 = wx.TextCtrl(
            self.nb_pane_2, wx.ID_ANY, "Lat-utf8", style=wx.TE_PROCESS_ENTER
        )
        self.text_12.SetMinSize((125, 23))
        self.sizer_9.Add(self.text_12, 0, wx.ALL, 6)

        self.sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(self.sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        self.sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        self.sizer_2.AddButton(self.button_CANCEL)

        self.sizer_2.Realize()

        self.nb_pane_2.SetSizer(self.sizer_7)

        self.nb_pane1.SetSizer(sizer_4)

        self.SetSizer(sizer_1)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        t1 = os.path.join("resources", "var", "dialog_settings.db.dat")
        try:
            with open(t1, "rb") as sp:
                data = pickle.load(sp)
                ex = data['key5']
                self.text_1.SetValue(ex['cyr_ansi_srt'])
                self.text_2.SetValue(ex['cyr_utf8_srt'])
                self.text_3.SetValue(ex['lat_utf8_srt'])
                self.text_4.SetValue(ex['transcribe'])
                self.text_5.SetValue(ex['cyr_utf8_txt'])
                self.text_6.SetValue(ex['lat_ansi_srt'])
                self.text_7.SetValue(ex['fixed_subs'])
                self.text_8.SetValue(ex['cleanup'])
                self.text_9.SetValue(ex["Cyr-ansi"])
                self.text_10.SetValue(ex["Lat-ansi"])
                self.text_11.SetValue(ex["Cyr-utf8"])
                self.text_12.SetValue(ex["Lat-utf-8"])

        except Exception as e:
            logger.debug(f"FileSetting: {e}")

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.onSave, self.button_OK)
        self.Bind(wx.EVT_CLOSE, self.onClose, id=-1)
        # end wxGlade

    def onSave(self, event):
        t1 = os.path.join("resources", "var", "dialog_settings.db.dat")
        try:
            s_dict = {
                'cyr_ansi_srt': self.text_1.GetValue(),
                'cyr_utf8_srt': self.text_2.GetValue(),
                'lat_utf8_srt': self.text_3.GetValue(),
                'transcribe': self.text_4.GetValue(),
                'cyr_utf8_txt': self.text_5.GetValue(),
                'lat_ansi_srt': self.text_6.GetValue(),
                'fixed_subs': self.text_7.GetValue(),
                'cleanup': self.text_8.GetValue(),
                "Cyr-ansi": self.text_9.GetValue(),
                "Lat-ansi": self.text_10.GetValue(),
                "Cyr-utf8": self.text_11.GetValue(),
                "Lat-utf8": self.text_12.GetValue(),
            }

            FILE_SETTINGS["key5"].update(s_dict)

            with open(t1, "wb") as d:
                pickle.dump(FILE_SETTINGS, d)

            name_data[1] = s_dict["cyr_utf8_txt"]
            name_data[2] = s_dict["lat_utf8_srt"]
            name_data[5] = s_dict

            with open(os.path.join("resources", "var", "file_ext.pkl"), "wb") as f:
                pickle.dump(s_dict, f)
        except Exception as e:
            logger.debug(f"FileSettings: {e}")
        self.Destroy()
        event.Skip()

    def onClose(self, event):
        self.Destroy()


class MyApp(wx.App):
    def OnInit(self):
        self.dialog = FileSettings(None, wx.ID_ANY, "")
        self.SetTopWindow(self.dialog)
        self.dialog.ShowModal()
        self.dialog.Destroy()
        return True


if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
