#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.0pre

import wx

# begin wxGlade: dependencies
# end wxGlade

import shelve


class fixerSettings(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: fixerSettings.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((339, 219))
        
        with shelve.open('resources\\var\\fixer_settings.db') as  sp:
            ex = sp['key1']
            cb1_s = ex['state1']; cb2_s = ex['state2']; cb3_s = ex['state3']
            cb4_s = ex['state4']; cb5_s = ex['state5']; cb6_s = ex['state6']        
        
        self.cb1 = wx.CheckBox(self, wx.ID_ANY, "cbox_1", style=wx.CHK_2STATE)
        self.cb1.SetValue(cb1_s)
        self.lb1 = wx.StaticText(self, wx.ID_ANY, "Popravi gapove", style=wx.ALIGN_LEFT)
        
        self.cb2 = wx.CheckBox(self, wx.ID_ANY, "cbox_2", style=wx.CHK_2STATE)
        self.cb2.SetValue(cb2_s)
        self.lb2 = wx.StaticText(self, wx.ID_ANY, "Poravnaj linije teksta", style=wx.ALIGN_LEFT)
        
        self.cb3 = wx.CheckBox(self, wx.ID_ANY, "cbox_3", style=wx.CHK_2STATE)
        self.cb3.SetValue(cb3_s)
        self.lb3 = wx.StaticText(self, wx.ID_ANY, u"Prika\u017ei linije sa gre\u0161kama u konvertovanom titlu", style=wx.ALIGN_LEFT)
        
        self.cb4 = wx.CheckBox(self, wx.ID_ANY, "cbox_4", style=wx.CHK_2STATE)
        self.cb4.SetValue(cb4_s)
        self.lb4 = wx.StaticText(self, wx.ID_ANY, u"Ukloni crtice na po\u010detku prvog reda", style=wx.ALIGN_LEFT)
        
        self.cb5 = wx.CheckBox(self, wx.ID_ANY, "cbox_5", style=wx.CHK_2STATE)
        self.cb5.SetValue(cb5_s)
        self.lb5 = wx.StaticText(self, wx.ID_ANY, u"Ukloni spejs iza crtice na po\u010detku", style=wx.ALIGN_LEFT)
        
        self.cb6 = wx.CheckBox(self, wx.ID_ANY, "cbox_6", style=wx.CHK_2STATE)
        self.cb6.SetValue(cb6_s)
        self.lb6 = wx.StaticText(self, wx.ID_ANY, u"Vi\u0161estruke spejseve u jedan", style=wx.ALIGN_LEFT)
        
        self.button_2 = wx.Button(self, wx.ID_ANY, "Cancel")
        self.button_1 = wx.Button(self, wx.ID_OK, "OK")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TOOL, self.onClose, id=-1)
        self.Bind(wx.EVT_BUTTON, self.on_cancel, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.on_ok, self.button_1)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: fixerSettings.__set_properties
        self.SetTitle("FixSubtitle settings")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("resources\\icons\\tool.ico", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((339, 219))
        self.SetFocus()
        
        self.cb1.SetMinSize((15, 15))
        self.lb1.SetMinSize((293, 16))
        self.lb1.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        
        self.cb2.SetMinSize((15, 15))
        self.lb2.SetMinSize((293, 16))
        self.lb2.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        
        self.cb3.SetMinSize((15, 15))
        self.lb3.SetMinSize((293, 16))
        self.lb3.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        
        self.cb4.SetMinSize((15, 15))
        self.lb4.SetMinSize((293, 16))
        self.lb4.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        
        self.cb5.SetMinSize((15, 15))
        self.lb5.SetMinSize((293, 16))
        self.lb5.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        
        self.cb6.SetMinSize((15, 15))
        self.lb6.SetMinSize((293, 16))
        self.lb6.SetFont(wx.Font(9, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        
        self.button_2.SetMinSize((80, 23))
        self.button_1.SetMinSize((80, 23))
        self.button_1.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: fixerSettings.__do_layout
        self.sizer_1 = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, ""), wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_2.Add(self.cb1, 0, wx.BOTTOM | wx.LEFT | wx.RIGHT, 2)
        self.sizer_2.Add(self.lb1, 1, wx.EXPAND | wx.LEFT, 2)
        self.sizer_1.Add(self.sizer_2, 0, wx.BOTTOM | wx.TOP, 2)
        self.sizer_3.Add(self.cb2, 0, wx.BOTTOM | wx.LEFT | wx.RIGHT, 2)
        self.sizer_3.Add(self.lb2, 1, wx.EXPAND | wx.LEFT, 2)
        self.sizer_1.Add(self.sizer_3, 0, wx.BOTTOM | wx.TOP, 2)
        self.sizer_4.Add(self.cb3, 0, wx.BOTTOM | wx.LEFT | wx.RIGHT, 2)
        self.sizer_4.Add(self.lb3, 1, wx.EXPAND | wx.LEFT, 2)
        self.sizer_1.Add(self.sizer_4, 0, wx.BOTTOM | wx.TOP, 2)
        self.sizer_5.Add(self.cb4, 0, wx.BOTTOM | wx.LEFT | wx.RIGHT, 2)
        self.sizer_5.Add(self.lb4, 1, wx.EXPAND | wx.LEFT, 2)
        self.sizer_1.Add(self.sizer_5, 0, wx.BOTTOM | wx.TOP, 2)
        self.sizer_6.Add(self.cb5, 0, wx.BOTTOM | wx.LEFT | wx.RIGHT, 2)
        self.sizer_6.Add(self.lb5, 1, wx.EXPAND | wx.LEFT, 2)
        self.sizer_1.Add(self.sizer_6, 0, wx.BOTTOM | wx.TOP, 2)
        self.sizer_7.Add(self.cb6, 0, wx.BOTTOM | wx.LEFT | wx.RIGHT, 2)
        self.sizer_7.Add(self.lb6, 1, wx.BOTTOM | wx.EXPAND | wx.LEFT, 2)
        self.sizer_1.Add(self.sizer_7, 0, wx.BOTTOM | wx.EXPAND | wx.TOP, 2)
        static_line_1 = wx.StaticLine(self, wx.ID_ANY)
        self.sizer_1.Add(static_line_1, 0, wx.ALL | wx.EXPAND, 4)
        sizer_8.Add(self.button_2, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.ALL, 1)
        sizer_8.Add(self.button_1, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.ALL, 1)
        self.sizer_1.Add(sizer_8, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT, 0)
        self.SetSizer(self.sizer_1)
        self.Layout()
        # end wxGlade

    def on_cancel(self, event):  # wxGlade: fixerSettings.<event_handler>
        if wx.ID_CANCEL:
            self.Destroy()
        event.Skip()
    
    def on_ok(self, event):  # wxGlade: fixerSettings.<event_handler>
        c1 = self.cb1.GetValue(); c2 = self.cb2.GetValue(); c3 = self.cb3.GetValue()
        c4 = self.cb4.GetValue(); c5 = self.cb5.GetValue(); c6 = self.cb6.GetValue()
        konf = [c1, c2, c3, c4, c5, c6]
        a = konf[0]; b = konf[1]; c = konf[2]; d = konf[3]; e = konf[4]; f = konf[5]
        if wx.ID_OK:
            with shelve.open('resources\\var\\fixer_settings.db') as s:
                s['key1'] = {'state1': a, 'state2': b, 'state3': c, 'state4': d, 'state5': e, 'state6': f,}            
            self.Destroy()
        event.Skip()
    
    def onClose(self, event):
        self.Destroy()
        event.Skip()
# end of class fixerSettings

class MyApp(wx.App):
    def OnInit(self):
        self.dialog = fixerSettings(None, wx.ID_ANY, "")
        self.SetTopWindow(self.dialog)
        self.dialog.ShowModal()
        # self.dialog.Destroy()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
