#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.9pre on Mon Aug 26 00:33:16 2019
#

import wx
import wx.html as html
import os

page = 'resources\\uputstvo.htm'

if not os.path.exists(page):
    # HTML String
    html = """
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
   <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
   <META NAME="GENERATOR" CONTENT="Mozilla/4.06 [en] (X11; I; Linux
   2.0.35 i686) [Netscape]">

</HEAD>
<BODY TEXT="#808080" BGCOLOR="#ebf5fb" LINK="#0000FF" VLINK="#FF0000" ALINK="#000088">

<H1><FONT COLOR="#000080">Subtitle Converter v - 0.5.7</FONT></H1>
<H2>
<FONT COLOR="#1a5276">Prečice:</FONT></H2>

<P><B><FONT COLOR="#000000">Ctrl+Shift+Y</B></FONT>
: Latinica u ćirilicu UTF-8 SRT, "Bulk" Latinica u ćirilicu UTF-8 SRT</P>

<P><B><FONT COLOR="#000000">Ctrl+Shift+F</B></FONT>
: FileSettings dijalog, predefinisani "pre presufiks" novih fajlova(lat,cyr,utf8...)</P>
    """
    
    # Write HTML String to file.html
    with open(page, "w") as file:
        file.write(html) 
    

class MyHtmlWindow(html.HtmlWindow):
    def __init__(self, parent, id):
        html.HtmlWindow.__init__(self, parent, id, style=wx.NO_FULL_REPAINT_ON_RESIZE)
        
    def OnSetTitle(self, title):
        super(MyHtmlWindow, self).OnSetTitle(title)

class MyManual(wx.Frame):
    def __init__(self, *args, **kwargs):
        wx.Frame.__init__(self, *args, **kwargs)
        self.SetSize((574, 495))
        self.SetTitle("Subtitle Converter - Uputstvo")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("resources\\icons\\tool.ico", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetSize((574, 495))
        
        htmlwin = MyHtmlWindow(self, -1)
        htmlwin.LoadPage(page)        
        
        self.Layout()
        # end wxGlade

# end of class MyDialog

class MyApp(wx.App):
    def OnInit(self):
        self.dialog = MyManual(None, wx.ID_ANY, "")
        self.SetTopWindow(self.dialog)
        self.dialog.Show()
        # self.dialog.Destroy()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
