#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.9pre on Mon Aug 26 00:33:16 2019
#
import sys
sys.path.append("../")
from settings import MAIN_SETTINGS 
import wx
import wx.html as html
import os

page = os.path.join('resources','docs','uputstvo.htm')

class MyHtmlWindow(html.HtmlWindow):
    def __init__(self, parent, id):
        html.HtmlWindow.__init__(self, parent, id, style=wx.NO_FULL_REPAINT_ON_RESIZE)
        
    def OnSetTitle(self, title):
        super(MyHtmlWindow, self).OnSetTitle(title)

class MyManual(wx.Frame):
    def __init__(self, *args, **kwargs):
        wx.Frame.__init__(self, *args, **kwargs)
        self.SetTitle("Subtitle Converter - Uputstvo")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap(os.path.join("resources","icons","tool.ico"), wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        try:
            size = MAIN_SETTINGS["Manual"]
            self.SetSize((size["W"], size["H"]))
        except:        
            self.SetSize((780, 680))
        
        htmlwin = MyHtmlWindow(self, -1)
        htmlwin.LoadPage(page)        
        self.Centre()
        self.Layout()
        # end wxGlade
        self.Bind(wx.EVT_SIZE, self.size_frame, id=-1)
        
    def size_frame(self, event):
        """"""
        width, height = event.GetSize()
        MAIN_SETTINGS["Manual"] = {"W": width, "H": height}
        event.Skip()    

# end of class MyDialog

class MyApp(wx.App):
    def OnInit(self):
        self.dialog = MyManual(None, wx.ID_ANY, "")
        self.SetTopWindow(self.dialog)
        self.dialog.Show()
        # self.dialog.Destroy()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
